#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# ///

import os
import sys
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
IMAGE_NAME = "myapp-builder"
CONTAINER_WORK_DIR = "/work"
WAF_DIR = f"{CONTAINER_WORK_DIR}/tools/waf"


def build_image():
    cmd = [
        "docker",
        "build",
        "-f",
        f"{SCRIPT_DIR}/Dockerfile",
        "-t",
        f"{IMAGE_NAME}",
        f"{SCRIPT_DIR}",
    ]
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


def run_container(command):
    uid = os.getuid()
    gid = os.getgid()

    cmd = [
        "docker",
        "run",
        "--rm",
        "--user",
        f"{uid}:{gid}",
        "-v",
        f"{SCRIPT_DIR}:{CONTAINER_WORK_DIR}",
        "-w",
        f"{CONTAINER_WORK_DIR}",
        "-e",
        f"WAFDIR={WAF_DIR}",
        "-e",
        f"HOST_PROJECT_PATH={SCRIPT_DIR}",
        f"{IMAGE_NAME}",
    ] + command
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


def main():
    build_image()

    waf_exec = f"{WAF_DIR}/waf-light"
    cmd = [
        "python3",
        f"{waf_exec}",
    ] + sys.argv[1:]

    run_container(cmd)


if __name__ == "__main__":
    main()
